### ISSUE TITLE
How much data that you use to train the pretrained model?

### ISSUE THREAD

**Issue by Cabbagehust2507** [Actasidiot/EFIFSTR#3]
Hi, I'm going to use your code to train model to recognize text but can I know about the amount of training data that you used? Thank you so much!

**Comment by Actasidiot** [comment]
You can check my paper https://arxiv.org/pdf/2009.07447.pdf. We use a huge amount (millions level) of training data (SynthText Syn90K SynAdd, IC13,15, COCO-T). If you wanna apply our model to your own dataset, you can download  our [pretrained model](https://drive.google.com/file/d/1s3LBOo_aLAG5nOmF91LhDUlHGvpaLa1_/view?usp=sharing) and finetune the model using your own dataset.
