### ISSUE TITLE
did you try STN on this model?

### ISSUE THREAD

**Issue by ximzzzzz** [Actasidiot/EFIFSTR#6]
recently, many researchers used to put STN(TPS) layer on first layer of their model.
have you tried also?
if so , is that worse than without STN?

**Comment by Actasidiot** [comment]
I haven't tried STN in my model yet. In my opinion, STN may have difficulty in dealing with text images where characters are randomly scattered. So I directly use 2D-attention to locate each character. You can try to combine STN with my model and test its performance. :)
