### ISSUE TITLE
Have you tried your model with another language like Chinese or Japanese?

### ISSUE THREAD

**Issue by Cabbagehust2507** [Actasidiot/EFIFSTR#7]
I see that your model is pretty good, so I wanna try it with my language or others. Do your model work with other languages well? Thank you.

**Comment by Actasidiot** [comment]
Thank you. I haven't tried my model on other languages but technically It can be applied to language systems such as Chinese and Japanese (where each character can be located in a word/sentence image), but may not fit in Arabic and Bangla (where the letters are normally joined together when they are written)

**Comment by Cabbagehust2507** [comment]
> Arabic and Bangla

Thank you :)
