### ISSUE TITLE
I trained model with my language but the result is bad...

### ISSUE THREAD

**Issue by Cabbagehust2507** [Actasidiot/EFIFSTR#9]
I trained model with my language but the result is bad, so I think maybe your "glyphs-325-fonts.npy" file with many fonts that is not compatible with my language, so how can I change that ".npy" file with my own fonts for my language?
Hope you can reply me soon! Thanks.

**Comment by Actasidiot** [comment]
you need to first render the character images of your language, using tools such as ImageFont in python,
``from PIL import ImageFont``,
(see https://pillow.readthedocs.io/en/3.0.x/reference/ImageFont.html for details.)

and then package them into npy,
for example, there are M fonts, N character categories, resolution is 32 * 32,
the npy you need to prepare is # N , M, 32*32

**Comment by Cabbagehust2507** [comment]
@Actasidiot 
Do you have any codes of that?

**Comment by Actasidiot** [comment]
> @Actasidiot
> Do you have any codes of that?

Sorry, I can't find those codes, you can search in google to find more examples about ImageFont. You can open my glyphs-325-fonts.npy and see how these glyphs are orgnized in the canvas.

**Comment by Cabbagehust2507** [comment]
> > @Actasidiot
> > Do you have any codes of that?
> 
> Sorry, I can't find those codes, you can search in google to find more examples about ImageFont. You can open my glyphs-325-fonts.npy and see how these glyphs are orgnized in the canvas.

okay, thank you so much!
